---
title: "Biostatistics"
---

Welcome to the website of the course "Biostatistics" of the master's programme "Translational Neuroscience" of the Julius-Maximilians-University Würzburg.

Classes will take place on Tuesdays, 10:00-12:00, at the seminar room 114 at the Marcusstr. 9-11.

Please use the navigation on the left to select the slides for each session (recommendation: Open in new tab).

We will use the following textbooks:

-   ST21: [Statistical Thinking for the 21st Century](https://statsthinking21.github.io/statsthinking21-core-site/index.html)

-   QF: [Fundamentals of Quantitative Data Analysis](https://psyteachr.github.io/quant-fun-v2/)

## Schedule

| Session | Date | Topic | Docent | Reading | Project Deadlines |
|----|----|----|----|----|----|
|  | 13.10. | *No class* |  |  | Read chapters and install software |
| 01 | 20.10. | General & R Intro | Hildebrandt | ST21: 1-3, QF: 1-3 | R & RStudio installed |
| 02 | 27.10. | Models | Hildebrandt | ST21: 4, QF: 4-6 |  |
| 03 | 03.11. | Data Wrangling | Hildebrandt | ST21: 4, QF: 4-6 |  |
| 04 | 10.11. | Data Visualization | Hildebrandt | QF: 7 |  |
| 05 | 17.11. | Probability | Hildebrandt | ST21: 7-8, QF: 8 | Dataset |
| 06 | 24.11. | Sampling | Hildebrandt | ST21: 7-8, QF: 8 |  |
| 07 | 01.12. | Hypothesis Testing | Schröder | ST21: 9-10 |  |
| 08 | 08.12. | Comparing Means & Categories | Schröder | ST21: 12, 15 | Research Question & Hypotheses |
| 09 | 15.12. | Exercises (t-Tests, Chi²) | Schröder | ST21: 12, 15 |  |
| 10 | 22.12. | (General) Linear Models | Schröder | ST21: 12-13 | First Analysis Ideas |
|  | 29.12. & 05.01. | *Holidays* |  |  |  |
| 11 | 12.01. | Exercises (GLM) | Schröder | ST21: 12-13 |  |
| 12 | 19.01. | Linear Mixed Models | Schröder | ST21: 14 | Analysis (with R scripts) |
| 13 | 26.01. | R Markdown for Reports | tbd |  |  |
| 14 | 02.02. | Troubleshooting Your Report | both |  | Send Questions via Email |
|  | 09.02. | ~~Reproducible Research~~ | video | ~~ST21: 18~~ | Report (with R Markdown) |
